export const TestMessages = [
  {
    id: 1,
    sender: 'Sarah Schmidt',
    subject: 'Figma-Mockups für das neue Dashboard (Teil 1)',
    body: 'Hi Jan, ich habe den ersten Teil der UI-Komponenten hochgeladen. Schau bitte mal rein. [Entwickler-Notiz: Zeitstempel identisch mit ID 12 / Ungelesen]',
    timestamp: '2026/08/18 14:22',
    seen: false,
  },
  {
    id: 2,
    sender: 'Max Mustermann',
    subject: 'Anfrage zu Projektdetails',
    body: 'Hallo Jan, könntest du mir bitte die aktuellen Designdokumente für das Message Center zukommen lassen? Ich benötige sie für das morgige Meeting.',
    timestamp: '2026/08/18 10:30',
    seen: true,
  },
  {
    id: 3,
    sender: 'Nils Wagner (HR)',
    subject: 'Urlaubsantrag Freigabe',
    body: 'Guten Morgen Jan, dein Urlaubsantrag für die zwei Wochen im September wurde erfolgreich im System hinterlegt. Schönen Urlaub vorab!',
    timestamp: '2026/08/17 14:22',
    seen: true,
  },
  {
    id: 4,
    sender: 'Christian Becker',
    subject: 'Strategieplanung 2030',
    body: 'Hallo Team, hier ist der erste Entwurf für unsere langfristige Roadmap. [Entwickler-Notiz: Zukunft-Timestamp / Sollte bei "Neueste oben" ganz oben stehen]',
    timestamp: '2030/01/01 12:00',
    seen: false,
  },
  {
    id: 5,
    sender: 'Lukas Weber',
    subject: 'Feedback zu den neuen Komponenten',
    body: 'Die Aufteilung von MessageFilter und MessageSearch gefällt mir extrem gut! Code sieht super modular aus. Lass uns morgen mal sprechen.',
    timestamp: '2026/08/16 16:45',
    seen: true,
  },
]
