export const TestMessages = [
  {
    id: 1,
    sender: 'Amtsgericht - Betreuungsgericht',
    reciever: 'you',
    subject: 'Bestellungsurkunde und Verpflichtung | Az. XVII 45/26',
    body: 'In der Betreuungssache des Betroffenen Max Mustermann erhalten Sie anbei die Ausfertigung des Beschlusses sowie Ihre Bestellungsurkunde. Die förmliche Verpflichtung erfolgt schriftlich. Wir bitten um Rücksendung des unterschriebenen Empfangsbekenntnisses.',
    timestamp: '2026/08/18 14:22',
    seen: false,
    important: false,
    folder: 'Inbox',
    attachments: [
      {
        name: 'Bestellungsurkunde_Mustermann.pdf',
        path: '/MessageData/Bestellungsurkunde_Mustermann.pdf',
        size: '1.2 MB',
      },
    ],
  },
  {
    id: 2,
    sender: 'Amtsgericht - Rechtspflege',
    reciever: 'you',
    subject: 'Aufforderung zur Einreichung des Vermögensverzeichnisses | Az. XVII 112/26',
    body: 'In der Betreuungssache Erika Schmidt werden Sie aufgefordert, das Anfangsvermögensverzeichnis gemäß § 1814 BGB innerhalb von vier Wochen einzureichen. Nutzen Sie hierfür bitte das beigefügte Formblatt.',
    timestamp: '2026/08/18 10:30',
    seen: false,
    important: false,
    folder: 'Inbox',
    attachments: [
      {
        name: 'Formblatt_Vermoegensverzeichnis.pdf',
        path: '/MessageData/Formblatt_Vermoegensverzeichnis.pdf',
        size: '540 KB',
      },
    ],
  },
  {
    id: 3,
    sender: 'Amtsgericht - Richterdienst',
    reciever: 'you',
    subject: 'Anhörungstermin zur Genehmigung der Wohnungskündigung | Az. XVII 92/25',
    body: 'Im Verfahren zur Genehmigung der Kündigung des Wohnraums von Herrn Karl Müller wurde ein Anhörungstermin anberaumt. Termin: 10.09.2026 um 10:00 Uhr, Zimmer 204. Das persönliche Erscheinen des Betreuers ist erforderlich.',
    timestamp: '2026/08/17 14:22',
    seen: false,
    important: true,
    folder: 'Inbox',
    attachments: [],
  },
  {
    id: 4,
    sender: 'Amtsgericht - Kasse',
    reciever: 'you',
    subject: 'Festsetzung der Betreuervergütung | Az. XVII 05/25',
    body: 'Ihrem Antrag auf Festsetzung der Vergütung für das Quartal 03/2025 im Fall Anna Wagner wurde stattgegeben. Der Betrag in Höhe von 1.320,00 Euro wurde zur Auszahlung an die Landeskasse angewiesen.',
    timestamp: '2025/11/14 11:05',
    seen: true,
    important: false,
    folder: 'Inbox',
    attachments: [
      {
        name: 'Verguetungsbeschluss_Wagner.pdf',
        path: '/MessageData/Verguetungsbeschluss_Wagner.pdf',
        size: '245 KB',
      },
    ],
  },
  {
    id: 5,
    sender: 'Amtsgericht - Geschäftsstelle',
    reciever: 'you',
    subject: 'Erinnerung: Sachstandsabfrage zum jährlichen Bericht | Az. XVII 89/25',
    body: 'In der Betreuungssache Werner Lehmann steht der jährliche Bericht über die persönlichen Verhältnisse noch aus. Bitte reichen Sie diesen zeitnah nach, da die Akte dem Richter zur Wiedervorlage vorliegt.',
    timestamp: '2026/08/16 16:45',
    seen: false,
    important: true,
    folder: 'Inbox',
    attachments: [],
  },
  {
    id: 6,
    sender: 'Amtsgericht - Rechtspflege',
    reciever: 'you',
    subject: 'Beanstandung der Rechnungslegung 2025 | Az. XVII 201/24',
    body: 'Bei der Prüfung der Rechnungslegung im Fall Klara Fischer wurden Unstimmigkeiten bei den Buchungen im November festgestellt. Es fehlen die Belege für die Positionen 12 und 14. Bitte reichen Sie die Kopien innerhalb von 14 Tagen nach.',
    timestamp: '2026/05/11 09:15',
    seen: true,
    important: false,
    folder: 'Inbox',
    attachments: [
      {
        name: 'Pruefprotokoll_Rechnungslegung.pdf',
        path: '/MessageData/Pruefprotokoll_Rechnungslegung.pdf',
        size: '310 KB',
      },
    ],
  },
  {
    id: 7,
    sender: 'Amtsgericht - Betreuungsgericht',
    reciever: 'you',
    subject: 'Mitteilung über den Tod des Betroffenen | Az. XVII 33/23',
    body: 'Das Gericht wurde darüber informiert, dass der Betroffene Heinz Becker am 28.08.2026 verstorben ist. Das Betreuungsverfahren ist beendet. Wir bitten um zeitnahe Rückgabe der Betreuungsurkunde und Einreichung des Schlussberichts.',
    timestamp: '2026/08/29 18:00',
    seen: false,
    important: false,
    folder: 'Inbox',
    attachments: [],
  },
  {
    id: 8,
    sender: 'Amtsgericht - Richterdienst',
    reciever: 'you',
    subject: 'Beschluss im Eilverfahren: Unterbringungsmaßnahme | Az. XVII 12/26',
    body: 'In der Rechtsleitungssache Walter Schulz ergeht im Wege der einstweiligen Anordnung der Beschluss zur geschlossenen Unterbringung. Die Genehmigung ist befristet bis zum 15.10.2026. Der Beschluss ist sofort wirksam.',
    timestamp: '2026/08/30 11:05',
    seen: false,
    important: true,
    folder: 'Inbox',
    attachments: [
      {
        name: 'Beschluss_Unterbringung_Schulz.pdf',
        path: '/MessageData/Beschluss_Unterbringung_Schulz.pdf',
        size: '890 KB',
      },
    ],
  },
  {
    id: 9,
    sender: 'Amtsgericht - Rechtspflege',
    reciever: 'you',
    subject: 'Aufforderung zur Stellungnahme: Einwilligungsvorbehalt | Az. XVII 402/25',
    body: 'Für das Verfahren zur Erweiterung des Aufgabenkreises bei Sabine Meyer liegt das ärztliche Gutachten nun vor. Das Gericht bittet um Ihre abschließende Stellungnahme als Betreuer bis zum 15.01.2026.',
    timestamp: '2025/12/20 08:12',
    seen: true,
    important: false,
    folder: 'Inbox',
    attachments: [],
  },
  {
    id: 10,
    sender: 'Amtsgericht - Geschäftsstelle',
    reciever: 'you',
    subject: 'Akteneinsicht gewährt | Az. XVII 144/26',
    body: 'Ihrem Antrag auf Akteneinsicht im Verfahren des Betroffenen Thomas Neumann wurde stattgegeben. Die Aktenbände liegen ab morgen für drei Werktage auf der Geschäftsstelle zur Einsichtnahme bereit.',
    timestamp: '2026/08/28 06:00',
    seen: true,
    important: false,
    folder: 'Inbox',
    attachments: [],
  },
  {
    id: 11,
    sender: 'Amtsgericht - Betreuungsgericht',
    reciever: 'you',
    subject: 'Anfrage zum Vorliegen einer Vorsorgevollmacht | Az. XVII 150/26',
    body: 'Im neu eingeleiteten Betreuungsverfahren für Hildegard Wagner wird geprüft, ob eine wirksame Vorsorgevollmacht existiert. Da Sie als potenzieller Betreuer vorgeschlagen wurden, bitten wir um Mitteilung, ob Ihnen Dokumente vorliegen.',
    timestamp: '2026/07/02 15:30',
    seen: true,
    important: false,
    folder: 'Inbox',
    attachments: [
      {
        name: 'Anfrage_Vorsorgevollmacht.pdf',
        path: '/MessageData/Anfrage_Vorsorgevollmacht.pdf',
        size: '150 KB',
      },
    ],
  },
  {
    id: 12,
    sender: 'Amtsgericht - Kasse',
    reciever: 'you',
    subject: 'Festsetzung der Betreuervergütung | Az. XVII 223/24',
    body: 'Ihrem Antrag auf Festsetzung der Vergütung für das Quartal 04/2025 im Fall Dieter Fuchs wurde stattgegeben. Der Betrag in Höhe von 980,00 Euro wurde zur Auszahlung an die Landeskasse angewiesen.',
    timestamp: '2026/02/10 09:40',
    seen: true,
    important: false,
    folder: 'Inbox',
    attachments: [
      {
        name: 'Verguetungsbeschluss_Fuchs.pdf',
        path: '/MessageData/Verguetungsbeschluss_Fuchs.pdf',
        size: '190 KB',
      },
    ],
  },
]
